name: flask-app

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: BugAccountantP2
      MYSQL_USER: flask
      MYSQL_PASSWORD: password
    ports: 
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d

  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: BugAccountantP2
      DATABASE_USER: flask
      DATABASE_PASSWORD: password
    depends_on:
      - db

volumes:
  db_data:
